version: "3.5"

services:

  # база данных
  db:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_DATABASE: appDb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - "./initDbFiles:/docker-entrypoint-initdb.d"
    restart: always

  # Динамические страницы и взимодействие с бд
  php-apache:
    build: "./php_apache"
    container_name: php-apache
    volumes:
      - "./src:/var/www/html"
      - "./php_apache/apache.conf:/etc/apache2/sites-available/000-default.conf"
      - "./php_apache/php.ini:/usr/local/etc/php/php.ini"
    restart: always
    depends_on:
      - db
      - redis

  # Административное управление бд
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my-php-myadmin
    ports:
      - 8081:80
    restart: always
    depends_on:
      - db
      - redis

  # Для отображения статических файлов и перенаправления на динамиечский контент
  web:
    image: nginx
    container_name: web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/static:/etc/nginx/data/static
    ports:
      - 1000:80

  redis:
    container_name: redis
    build: "./redis"